jobs:
  test-and-build:
    docker:
      - image: fadhilnurmahardi/golang_coveralls:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: get depedency
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: do testing
          command: CGO_ENABLED=0 go test ./... -coverprofile=/tmp/coverage.out
      - run:
          name: build
          command: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go install -a -tags netgo -ldflags '-w -extldflags "-static"' ./...
      - store_artifacts:
          path: /tmp/coverage.out
      - store_artifacts:
          path: /go/bin/app
workflows:
  version: 2
  untagged-build-beta:
    jobs:
      - test-and-build